### ISSUE TITLE
Review- Design Doc

### ISSUE THREAD

**Issue by jmeyer90** [jmkaneshiro/stayontrack#1]
MVP
- I'm not familiar with the website, but I poked around the site and your design MVPs look well detailed. You must also include MVPs for user auth and the readme.

Schema
- Include all associations (has_many, has_many through, etc) in your schema below each respective table.

Sample State
- In your frontend state, when going to a show page for a specific slice of state, that object will want to hold onto an array of foreign key ids Ex: if a user has_many user_projects, then that user should have an array of user_project_ids. And if that user is an author of certain projects, it should hold an array of authored_project_ids.

Routes
- You routes look great! Feel free to move on from here.

**Comment by jmkaneshiro** [comment]
Discussed in more detail with Justin. 

## Will work on the following: 
### MVP
+ feature authentication in my MVP
+ include reminder to complete ReadMe in the MVP
### Schema
+ include associations (went over details of handling through associations)
+ change the `stories` `story_state` into an array of strings
### Story State
+ include foreign keys in arrays for each key, ex: `users: { id: 1, username: "test", projects_owned: [7, 12, 13] }`
### Frontend Routes
+ `/` page should go to the dashboard where you select your project
+ nav bars are child containers of each project
### Feature: Stories
+ can use lazy initialization for labels
### Bonuses (don't work on these features unless time permits)
+ link to story page outside project
+ scoring features

**Comment by jmkaneshiro** [comment]
@jmeyer90 Hey there! I went ahead and addressed your feedback on all the items in the wiki. The main one I still feel shaky on is the way that I've described my frontend routes. Please re-open this issue, if you have any advice on ways to clean that part up any further. Thank you!
